In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df=pd.read_csv('glass.csv')

In [5]:
df.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [6]:
df.shape

(214, 10)

In [7]:
df.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'Type'], dtype='object')

1. we need to predict the type of teh glass based on the features RI,Na,Mg,Al,Si,K,Ca,Ba,Fe.
2. all the features are numerical


In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [9]:
np.unique(df['Type'])

array([1, 2, 3, 5, 6, 7])

this shows that there are 6 types of glass which means its a multiclass classification .


In [10]:
df['y']=(df['Type']==1).astype(int)
print(np.unique(df['y']))

[0 1]


In [11]:
df=df.drop(columns=['Type'])

In [12]:
df.columns

Index(['RI', 'Na', 'Mg', 'Al', 'Si', 'K', 'Ca', 'Ba', 'Fe', 'y'], dtype='object')

In [13]:
X=df.drop(columns=['y']).values
y=df['y'].values

In [14]:
X

array([[ 1.52101, 13.64   ,  4.49   , ...,  8.75   ,  0.     ,  0.     ],
       [ 1.51761, 13.89   ,  3.6    , ...,  7.83   ,  0.     ,  0.     ],
       [ 1.51618, 13.53   ,  3.55   , ...,  7.78   ,  0.     ,  0.     ],
       ...,
       [ 1.52065, 14.36   ,  0.     , ...,  8.44   ,  1.64   ,  0.     ],
       [ 1.51651, 14.38   ,  0.     , ...,  8.48   ,  1.57   ,  0.     ],
       [ 1.51711, 14.23   ,  0.     , ...,  8.62   ,  1.67   ,  0.     ]])

In [15]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
import random
import numpy as np

def traintestsplit(X, y, testsize=0.3, randomseed=None):
    data = list(zip(X, y))

    if randomseed:
        random.seed(randomseed)

    random.shuffle(data)

    idx = int(len(data) * (1 - testsize))

    train = data[:idx]
    test = data[idx:]

    X_train, y_train = zip(*train)
    X_test, y_test = zip(*test)

    return np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test)

In [17]:
X_train,X_test,y_train,y_test=traintestsplit(X,y,0.2,42)

In [34]:
print(X_train[0])
print(X_test[0])

[ 1.51658 14.8      0.       1.99    73.11     0.       8.28     1.71
  0.     ]
[ 1.51569 13.24     3.49     1.47    73.25     0.38     8.03     0.
  0.     ]


# scaling the inputs
standard scaler-> z=(x-μ)/σ

In [35]:
class StandardScaler:
  def __init__(self):
    self.mean=None
    self.std=None

  def fit(self,X):
    X=np.array(X)
    self.mean=X.mean(axis=0)
    self.std=X.std(axis=0)

  def transform(self,X):
    X=np.array(X)
    X_scaled=(X-self.mean)/self.std
    return X_scaled

  def fit_transform(self,X):
    X=np.array(X)
    self.fit(X)
    return self.transform(X)

  def inverse_transform(self,X_scaled):
    X_scaled=np.array(X_scaled)
    X=X_scaled*self.std+self.mean
    return X

In [20]:
scaler=StandardScaler()
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [36]:
print(X_train[0])

[ 1.51658 14.8      0.       1.99    73.11     0.       8.28     1.71
  0.     ]


In [22]:
print(X_train_scaled[0])

[-0.60345604  1.79520791 -1.88856806  1.1043651   0.60776338 -0.72041984
 -0.49899921  3.30189801 -0.5905165 ]


In [23]:
def sigmoid(z):
  return 1/(1+np.exp(-z))

In [24]:
def predict_prob(X,w,b):
  z=np.dot(X,w)+b
  p=sigmoid(z)
  return p

In [38]:
def loss(y,p):
  return -np.mean(y*np.log(p)+(1-y)*np.log(1-p))

In [37]:
def update_weights(X,y,w,b,lr):
  p=predict_prob(X, w, b)
  error=p-y
  dw=np.dot(X.T, error)/len(y)
  db=np.mean(error)
  w=w-lr*dw
  b=b-lr*db
  return w,b

In [40]:
w=np.zeros(X_train.shape[1])
b=0.0
lr=0.1
epochs=200

In [41]:
for i in range(epochs):
    w,b=update_weights(X_train_scaled,y_train,w,b,lr)
    print(f'epoch {i+1}: {loss(y_train,predict_prob(X_train_scaled,w,b))}')

epoch 1: 0.6814387068624147
epoch 2: 0.6707467420252893
epoch 3: 0.6609660428873784
epoch 4: 0.6520001892586949
epoch 5: 0.6437619926718353
epoch 6: 0.6361733840029303
epoch 7: 0.6291649603732207
epoch 8: 0.6226753335094513
epoch 9: 0.6166503836542883
epoch 10: 0.6110424903357771
epoch 11: 0.6058097855496606
epoch 12: 0.600915455978052
epoch 13: 0.5963271076998847
epoch 14: 0.5920161981518167
epoch 15: 0.5879575346713644
epoch 16: 0.584128835809179
epoch 17: 0.5805103499806501
epoch 18: 0.5770845253920853
epoch 19: 0.5738357251430061
epoch 20: 0.5707499817173758
epoch 21: 0.5678147855657598
epoch 22: 0.5650189030422569
epoch 23: 0.5623522195310124
epoch 24: 0.5598056041411027
epoch 25: 0.5573707928469728
epoch 26: 0.5550402873967659
epoch 27: 0.5528072677015935
epoch 28: 0.5506655157575836
epoch 29: 0.5486093494437748
epoch 30: 0.546633564787727
epoch 31: 0.5447333855023915
epoch 32: 0.5429044187773017
epoch 33: 0.5411426164591541
epoch 34: 0.5394442408853836
epoch 35: 0.53780583474300

In [42]:
def predict_label(p,thr=0.5):
  return (p>=thr).astype(int)

In [43]:
y_pred=predict_label(predict_prob(X_test_scaled,w,b),0.7)

In [44]:
np.mean(y_pred==y_test)

np.float64(0.6511627906976745)

In [45]:
y_pred=predict_label(predict_prob(X_test_scaled,w,b),0.8)
np.mean(y_pred==y_test)

np.float64(0.6046511627906976)